Repository NASA-IMPACT/veda-ui, pull requests merged in 2024-12, with the labels that each got.

#1320 fix: 1135 wiring up veda config
  app/scripts/components/common/layout-root/index.tsx
  app/scripts/components/common/page-footer/index.tsx
  app/scripts/components/common/page-header/default-config.ts
  app/scripts/components/common/page-header/nav/create-dynamic-nav-menu-list.tsx
  app/scripts/components/common/page-header/nav/nav-item-cta.tsx
  mock/veda.config.js
  parcel-resolver-veda/index.d.ts
  parcel-resolver-veda/index.js
Labels: design system change

#1310 chore: Remove linkProperties from DataCatalog Component
  app/scripts/components/common/card/index.tsx
  app/scripts/components/common/catalog/catalog-card.tsx
  app/scripts/components/common/catalog/catalog-content.tsx
  app/scripts/components/common/catalog/index.tsx
  app/scripts/components/data-catalog/container.tsx
  app/scripts/components/exploration/components/dataset-selector-modal/index.tsx
Labels: refactor

#1314 fix: Update mappings to system tokens instead of theme tokens
  app/scripts/styles/_uswds-theme.scss
  app/scripts/styles/_veda-ui-theme-vars.scss
Labels: design system change

#1306 chore: Update SETUP.md to include part about format on save
  docs/development/SETUP.md
Labels: documentation
